### ISSUE TITLE
Update action to run on node 20

### ISSUE THREAD

**Issue by kacus** [waycarbon/github-action-container-cleanup#2]
Node 16 GitHub Actions are deprecated.
[Changelog](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)

**Comment by gchamon** [comment]
Hey @kacus I don't have access to the organization anymore and I can't tell anyone owns this repo, so the best course of action would be to fork and fix it yourself.

**Comment by kacus** [comment]
Thanks for the quick reply! As you suggested, I have created a fork and created a new action [here](https://github.com/marketplace/actions/cleanup-docker-containers-created-by-github-action) for anyone who still needs this action.
